-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

DROP EXTENSION pg_net;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

CREATE TABLE public.expenses (
  id          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  amount      numeric,
  description text,
  category    text,
  date        date,
  user_id     uuid                     DEFAULT auth.uid()
);

ALTER TABLE public.expenses
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);

GRANT ALL ON public.expenses TO anon;

GRANT ALL ON public.expenses TO authenticated;

GRANT ALL ON public.expenses TO service_role;

CREATE POLICY "Enable delete for users based on user_id" ON public.expenses
  FOR DELETE
  USING ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable insert for authenticated users only" ON public.expenses
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Enable insert for users based on user_id" ON public.expenses
  FOR INSERT
  WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable update for all users" ON public.expenses
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable users to view their own data only" ON public.expenses
  FOR SELECT
  TO authenticated
  USING ((( SELECT auth.uid() AS uid) = user_id));
