-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TABLE public.categories (
  id         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  category   text                     DEFAULT ''::text,
  user_id    uuid                     DEFAULT auth.uid()
);

COMMENT ON TABLE public.categories IS 'Expense categories for each user';

ALTER TABLE public.categories
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.categories
  ADD CONSTRAINT categories_category_key UNIQUE (category);

ALTER TABLE public.categories
  ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

GRANT ALL ON public.categories TO anon;

GRANT ALL ON public.categories TO authenticated;

GRANT ALL ON public.categories TO service_role;

CREATE POLICY "Enable delete for users based on user_id" ON public.categories
  FOR DELETE
  USING ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable insert for authenticated users only" ON public.categories
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Enable insert for users based on user_id" ON public.categories
  FOR INSERT
  WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable users to view their own data only" ON public.categories
  FOR SELECT
  TO authenticated
  USING ((( SELECT auth.uid() AS uid) = user_id));
